### ISSUE TITLE
Doesn't work with php >= 5.6

### ISSUE THREAD

**Issue by jhoff** [funkjedi/composer-include-files#1]
From `vendor/composer/autoload_real.php`:

```
...
        $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION');
...
        if ($useStaticLoader) {
            $includeFiles = Composer\Autoload\ComposerStaticInit5ee7f927e9df5b9abb8371ee2d7c8671::$files;
        } else {
            $includeFiles = require __DIR__ . '/autoload_files.php';
        }
...
```

On PHP version 5.6 or higher, composer uses the static loader instead of requiring autoload_files, so this plugin stops working as expected.

**Comment by pfbernardo** [comment]
Hi,

Are you guys merging the pull request into master?

This would help me alot.

Thanks.

**Comment by jhoff** [comment]
This seems to be an abandoned project. I'm using my fork by overriding the repo in composer :/
