### ISSUE TITLE
Create new release for composer 2.0 support

### ISSUE THREAD

**Issue by duxthefux** [funkjedi/composer-include-files#12]
Hey,

it would be really cool if you could create a new release which has the composer 2.0 support.

Thanks!

**Comment by dkaufmann96** [comment]
Agreed.

**Comment by Yurunsoft** [comment]
Me too

**Comment by simonhamp** [comment]
@funkjedi It looks like the work is done, this just needs to be tagged for Packagist's benefit. I have tested and can confirm it all works.

**Comment by simonhamp** [comment]
Even better (as it doesn't look like a breaking change) if you can tag it as v1.1.0, that would make a few lives easier

**Comment by RobvH** [comment]
Builds are now breaking with composer 2.0 release. Probably a conversation we need to have about not automatically updating major versions of composer, for sure. However, fyi - composer 2 is out and this is now an issue until a release is cut. :) Any thing I can do to help?

**Comment by simonhamp** [comment]
Thanks @funkjedi ! 🎉
